import fs from 'fs';
import path from 'path';
import { feature } from 'topojson-client';

/**
 * Generates src/geo/world.ts — a flat, dependency-free world map for the
 * map_card layout (copilot.md §5.15): every country as a pre-projected SVG
 * path string, plus the projection helper constants and per-region frames.
 * Source: world-atlas countries-110m (Natural Earth, public domain), decoded
 * once here with topojson-client so the renderer bundles plain data with
 * zero runtime deps and zero network fetches. Re-run after changing REGIONS.
 *
 *   npx tsx scripts/gen-map.ts
 */

// Projection: plain equirectangular into a 2000x1000 canvas.
const W = 2000;
const H = 1000;
const px = (lon: number): number => ((lon + 180) / 360) * W;
const py = (lat: number): number => ((90 - lat) / 180) * H;

// Region frames as lon/lat bounds (projected below). Keys must match the
// PHP validator's MAP_REGIONS whitelist.
const REGION_BOUNDS: Record<string, { lon: [number, number]; lat: [number, number] }> = {
  world: { lon: [-180, 180], lat: [-58, 84] },
  europe: { lon: [-26, 46], lat: [34, 72] },
  asia: { lon: [24, 152], lat: [-11, 62] },
  africa: { lon: [-20, 56], lat: [-36, 38] },
  north_america: { lon: [-170, -50], lat: [6, 76] },
  south_america: { lon: [-86, -32], lat: [-57, 14] },
  oceania: { lon: [108, 182], lat: [-50, 2] },
};

const topoFile = path.join(__dirname, '..', 'node_modules', 'world-atlas', 'countries-110m.json');
const topo = JSON.parse(fs.readFileSync(topoFile, 'utf8'));
const fc = feature(topo, topo.objects.countries) as unknown as {
  features: { id?: string; properties?: { name?: string }; geometry: { type: string; coordinates: unknown } }[];
};

const fmt = (n: number): string => String(Math.round(n * 10) / 10);

const ringToPath = (ring: [number, number][]): string => {
  // Rings that cross the antimeridian (Russia, Fiji) would otherwise draw a
  // line clean across the map — break the path at any >170° lon jump and
  // skip the closing Z when a break happened (closing would re-draw the seam).
  let d = '';
  let split = false;
  let prevLon: number | null = null;
  ring.forEach(([lon, lat], i) => {
    const jump = prevLon !== null && Math.abs(lon - prevLon) > 170;
    if (jump) split = true;
    d += `${i === 0 || jump ? 'M' : 'L'}${fmt(px(lon))} ${fmt(py(lat))}`;
    prevLon = lon;
  });
  return split ? d : d + 'Z';
};

const paths: string[] = [];
for (const f of fc.features) {
  // Antarctica dominates the bottom of the frame and never carries a pin.
  if (f.properties?.name === 'Antarctica') continue;
  const g = f.geometry;
  if (!g) continue;
  const polys: [number, number][][][] =
    g.type === 'Polygon'
      ? [g.coordinates as [number, number][][]]
      : g.type === 'MultiPolygon'
        ? (g.coordinates as [number, number][][][])
        : [];
  let d = '';
  for (const poly of polys) {
    // Outer ring only — 110m holes (lakes) are invisible at render size.
    d += ringToPath(poly[0]);
  }
  if (d) paths.push(d);
}

const regions: Record<string, { x: number; y: number; w: number; h: number }> = {};
for (const [name, b] of Object.entries(REGION_BOUNDS)) {
  const x = px(b.lon[0]);
  const y = py(b.lat[1]); // north edge = smaller y
  regions[name] = {
    x: Math.round(x),
    y: Math.round(y),
    w: Math.round(px(b.lon[1]) - x),
    h: Math.round(py(b.lat[0]) - y),
  };
}

const out = `// GENERATED by scripts/gen-map.ts — do not edit by hand.
// Source: world-atlas countries-110m (Natural Earth, public domain),
// pre-projected with a plain equirectangular projection so the map_card
// layout needs no runtime geo deps.

export const MAP_W = ${W};
export const MAP_H = ${H};

/** Project a lat/lon into the map's coordinate space. */
export const projectLat = (lat: number): number => ((90 - lat) / 180) * MAP_H;
export const projectLon = (lon: number): number => ((lon + 180) / 360) * MAP_W;

/** Region framing rects (same space); keys mirror the PHP MAP_REGIONS list. */
export const MAP_REGIONS: Record<string, { x: number; y: number; w: number; h: number }> = ${JSON.stringify(regions, null, 2)};

/** Every country as one SVG path (outer rings, Antarctica dropped). */
export const WORLD_PATHS: string[] = ${JSON.stringify(paths)};
`;

const outFile = path.join(__dirname, '..', 'src', 'geo', 'world.ts');
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);
console.log(`wrote ${outFile} (${paths.length} countries, ${Math.round(out.length / 1024)} KB)`);
