import fs from 'fs';
import path from 'path';

/**
 * Extracts a curated subset of Lucide icons (ISC license) from lucide-static
 * into src/icons/lucide.ts as inline stroke primitives, so the icon_grid card
 * (copilot.md §5.6) can stroke-draw them with zero runtime deps and zero
 * network fetches. Re-run after changing CURATED. Also refreshes the
 * `icon_grid.icons` whitelist in the PHP registry so the planner prompt and
 * validator can never drift from what the renderer actually bundles.
 *
 *   npx tsx scripts/gen-icons.ts
 */

// ~120 explainer-vocabulary icons: objects, actions, data, tech, commerce,
// science, communication — the nouns an explainer script actually mentions.
const CURATED = [
  'activity', 'alarm-clock', 'anchor', 'antenna', 'archive', 'arrow-down', 'arrow-right', 'arrow-up',
  'atom', 'award', 'axe', 'badge-check', 'banknote', 'battery-charging', 'bell', 'bike',
  'bolt', 'book-open', 'box', 'brain', 'briefcase', 'bug', 'building', 'building-2',
  'bus', 'calculator', 'calendar', 'camera', 'car', 'check', 'chef-hat', 'circle-dollar-sign',
  'clock', 'cloud', 'cloud-rain', 'code', 'cog', 'coins', 'compass', 'cpu',
  'credit-card', 'crown', 'database', 'dna', 'dollar-sign', 'download', 'droplet', 'dumbbell',
  'earth', 'eye', 'factory', 'feather', 'file-text', 'film', 'flag', 'flame',
  'flask-conical', 'gamepad-2', 'gauge', 'gavel', 'gem', 'gift', 'graduation-cap', 'hammer',
  'hand-coins', 'heart', 'heart-pulse', 'home', 'hourglass', 'key', 'landmark', 'laptop',
  'leaf', 'lightbulb', 'link', 'lock', 'magnet', 'mail', 'map', 'map-pin',
  'megaphone', 'message-circle', 'mic', 'microscope', 'moon', 'mountain', 'music', 'newspaper',
  'package', 'palette', 'pencil', 'phone', 'piggy-bank', 'pill', 'plane', 'plug',
  'puzzle', 'radio', 'recycle', 'rocket', 'satellite', 'scale', 'scissors', 'search',
  'server', 'shield', 'ship', 'shopping-cart', 'smartphone', 'sprout', 'star', 'stethoscope',
  'sun', 'target', 'telescope', 'tent', 'thermometer', 'timer', 'tractor', 'train-front',
  'trees', 'trending-down', 'trending-up', 'trophy', 'truck', 'umbrella', 'users', 'wallet',
  'wand-sparkles', 'watch', 'wifi', 'wrench', 'x', 'zap',
];

const ICONS_DIR = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const OUT_TS = path.join(__dirname, '..', 'src', 'icons', 'lucide.ts');
const REGISTRY = path.join(
  __dirname, '..', '..', 'viralforgebackend', 'modules', 'Project', 'Resources', 'explainer_registry.json'
);

type IconNode = [string, Record<string, string>];

const SHAPE_TAGS = ['path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse'];

const parseSvg = (svg: string): IconNode[] => {
  const nodes: IconNode[] = [];
  const re = new RegExp(`<(${SHAPE_TAGS.join('|')})\\s([^/>]*)/?>`, 'g');
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    const attrs: Record<string, string> = {};
    const attrRe = /([a-zA-Z-]+)="([^"]*)"/g;
    let a: RegExpExecArray | null;
    while ((a = attrRe.exec(m[2])) !== null) {
      attrs[a[1]] = a[2];
    }
    nodes.push([m[1], attrs]);
  }
  return nodes;
};

const icons: Record<string, IconNode[]> = {};
const missing: string[] = [];
for (const name of CURATED) {
  const file = path.join(ICONS_DIR, `${name}.svg`);
  if (!fs.existsSync(file)) {
    missing.push(name);
    continue;
  }
  const nodes = parseSvg(fs.readFileSync(file, 'utf8'));
  if (nodes.length) icons[name] = nodes;
  else missing.push(name);
}
if (missing.length) {
  console.error('MISSING from lucide-static (fix CURATED):', missing.join(', '));
  process.exit(1);
}

const banner = `// GENERATED by scripts/gen-icons.ts — do not edit by hand.
// Source: lucide-static (ISC license, https://lucide.dev). ${Object.keys(icons).length} icons,
// stored as raw stroke primitives on a 24x24 grid (stroke-width 2, round caps).

export type IconNode = [tag: string, attrs: Record<string, string>];

export const LUCIDE_ICONS: Record<string, IconNode[]> = `;

fs.mkdirSync(path.dirname(OUT_TS), { recursive: true });
fs.writeFileSync(OUT_TS, banner + JSON.stringify(icons, null, 2) + ';\n');
console.log(`wrote ${OUT_TS} (${Object.keys(icons).length} icons)`);

// Sync the registry whitelist (the planner may only pick these names).
const registry = JSON.parse(fs.readFileSync(REGISTRY, 'utf8'));
registry.icon_grid = { ...(registry.icon_grid ?? {}), icons: Object.keys(icons).sort() };
fs.writeFileSync(REGISTRY, JSON.stringify(registry, null, 2) + '\n');
console.log(`synced icon whitelist into explainer_registry.json`);
